**4.1数据类型**

In [1]:
import tensorflow as tf

#创建标量
a = 1.2
aa = tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [2]:
#打印信息
x = tf.constant([1.2, 3.3])
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 3.3], dtype=float32)>

In [3]:
x.numpy()

array([1.2, 3.3], dtype=float32)

In [4]:
#创建向量
a = tf.constant([1.2])
a, a.shape

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

In [5]:
#创建两个元素的向量
a = tf.constant([1.2, 3.])
a, a.shape

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 3. ], dtype=float32)>,
 TensorShape([2]))

In [6]:
#创建矩阵
a = tf.constant([[1,2],[3,4],[5,6],[7,8]])
a, a.shape

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>, TensorShape([4, 2]))

In [7]:
#4.1.2 字符串类型
a = tf.constant('Hello, Deep Learning.')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

In [8]:
tf.strings.lower(a)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello, deep learning.'>

In [9]:
#4.1.3 布尔类型
a = tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [10]:
a = tf.constant([True, True])
a

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [11]:
a = tf.constant(True)
a == True

<tf.Tensor: shape=(), dtype=bool, numpy=True>

**4.2 数值精度**

In [12]:
#指定保存精度
tf.constant(123456789,dtype=tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [13]:
tf.constant(123456789,dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

In [14]:
import numpy as np

np.pi

3.141592653589793

In [15]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

In [16]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [17]:
#4.2.1 读取精度
print('before:', a.dtype)

before: <dtype: 'bool'>


In [18]:
if a.dtype != tf.float32:
  a = tf.cast(a, tf.float32)

print('after:',a.dtype)

after: <dtype: 'float32'>


In [19]:
#4.2.2 类型转换
a = tf.constant(np.pi, dtype=tf.float32)

In [20]:
tf.cast(a,tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=3.1415927410125732>

In [21]:
a=tf.constant(123456789,dtype=tf.int16)

In [22]:
tf.cast(a, tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [23]:
a = tf.constant([True,False])

In [24]:
tf.cast(a, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [25]:
a = tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

**4.3 待优化的张量**

In [26]:
#转化张量
a = tf.constant([-1, 0, 1, 2])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

In [27]:
#直接创建
a = tf.Variable([[1, 2], [3, 4]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

**4.4 创建张量**

In [28]:
#4.4.1 从Numpy,List对象创建
tf.convert_to_tensor([1, 2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [29]:
tf.convert_to_tensor(np.array([[1,2.], [3,4]]))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [30]:
#4.4.2 创建全0，全1张量
#创建为0和为1的标量张量
tf.zeros([]),tf.ones([])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [31]:
#创建为0和为1的向量
tf.zeros([1]), tf.ones([1])

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

In [32]:
#创建为0和为1的矩阵
tf.zeros([2,2]),tf.ones([2,2])

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [33]:
a = tf.ones([2, 3])
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [34]:
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [35]:
a=tf.zeros([3,2])
tf.ones_like(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [36]:
tf.ones(a.shape)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [37]:
#4.4.3 创建自定义数值张量
tf.fill([], -1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [38]:
tf.fill([1], -1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1], dtype=int32)>

In [39]:
tf.fill([2,2],99)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]], dtype=int32)>

In [40]:
#4.4.4 创建已知分布的张量
tf.random.normal([2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.05276087,  0.6514136 ],
       [-0.17628177, -1.3439068 ]], dtype=float32)>

In [41]:
tf.random.normal([2, 2], mean=1, stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.8692498 , 0.44219083],
       [3.922211  , 0.68198705]], dtype=float32)>

In [42]:
tf.random.uniform([2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.52348137, 0.5868044 ],
       [0.43949902, 0.572253  ]], dtype=float32)>

In [43]:
tf.random.uniform([2, 2], maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.764846 , 5.780205 ],
       [1.0867405, 2.8003883]], dtype=float32)>

In [44]:
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[65, 56],
       [58, 81]], dtype=int32)>

In [45]:
#4.4.5 创建序列
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [46]:
tf.range(10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [47]:
tf.range(1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

**4.5 张量的典型应用**

In [48]:
#4.5.1 标量
out=tf.random.uniform([4,10])
y=tf.constant([2,3,2,0])
y=tf.one_hot(y,depth=10)
loss=tf.keras.losses.mse(y,out)
loss=tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.40287435, shape=(), dtype=float32)


In [49]:
#4.5.2 向量
z = tf.random.normal([4, 2])
b = tf.zeros([2])
z = z+b
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.23056273,  0.26016763],
       [ 0.6725084 ,  0.2943404 ],
       [ 1.457527  ,  0.33321536],
       [-0.55863744, -0.02053401]], dtype=float32)>

In [50]:
fc=tf.keras.layers.Dense(3)
fc.build(input_shape=(2, 4))
fc.bias

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [51]:
fc.weights

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.022605  ,  0.36297357,  0.04634613],
        [ 0.7343725 ,  0.06022912,  0.6461388 ],
        [ 0.60289216, -0.4740405 , -0.15052295],
        [-0.14204681,  0.19825399,  0.8003795 ]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [52]:
fc.variables

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.022605  ,  0.36297357,  0.04634613],
        [ 0.7343725 ,  0.06022912,  0.6461388 ],
        [ 0.60289216, -0.4740405 , -0.15052295],
        [-0.14204681,  0.19825399,  0.8003795 ]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [53]:
#4.5.3 矩阵
x=tf.random.normal([2,4])
w=tf.ones([4,3])
b=tf.zeros([3])
o = x@w+b
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.0728416 , 1.0728416 , 1.0728416 ],
       [0.47782445, 0.47782445, 0.47782445]], dtype=float32)>

In [54]:
o = tf.matmul(x, w)+b
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.0728416 , 1.0728416 , 1.0728416 ],
       [0.47782445, 0.47782445, 0.47782445]], dtype=float32)>

In [55]:
fc=tf.keras.layers.Dense(3)
fc.build(input_shape=(2,4))
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.6384791 ,  0.477857  , -0.7562433 ],
       [ 0.07078236,  0.4418186 , -0.6727543 ],
       [-0.44208238, -0.830996  , -0.43854073],
       [-0.6720139 , -0.30505085,  0.5916233 ]], dtype=float32)>

In [56]:
#4.5.4 3维张量
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.imdb.load_data(num_words=10000)
len(x_train[0]),len(x_train[1])

17473536/17464789 [==============================] - 0s 0us/step


(218, 189)

In [57]:
x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=80)
x_train.shape

(25000, 80)

In [58]:
embedding = tf.keras.layers.Embedding(10000, 100)
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])

In [59]:
#4.5.5 4维张量
x = tf.random.normal([4, 32, 32, 3])
layer = tf.keras.layers.Conv2D(16, kernel_size=3)
out= layer(x)
out.shape

TensorShape([4, 30, 30, 16])

In [60]:
layer.kernel.shape

TensorShape([3, 3, 3, 16])

**4.6 索引与切片**

In [61]:
x=tf.random.normal([4,32,32,3])

In [62]:
x[0]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-0.84729683, -0.9580132 , -0.22700632],
        [-0.90364957,  0.72101486, -0.6206897 ],
        [-0.9568486 ,  0.02505994,  1.0152814 ],
        ...,
        [ 0.4273543 , -0.11339796, -0.20915268],
        [-0.5567593 ,  1.0180682 , -0.18325847],
        [ 1.0060095 , -1.6604997 ,  1.5379963 ]],

       [[-0.3115705 ,  0.66871995, -1.3308023 ],
        [-1.3819488 ,  0.5435539 , -0.16147228],
        [-0.46464762, -2.094918  , -2.1984982 ],
        ...,
        [-0.55574125,  1.139492  ,  0.7941052 ],
        [ 1.4219272 ,  1.5203484 , -0.33960515],
        [ 0.50826496,  0.7862004 ,  0.5318456 ]],

       [[-0.14322305, -0.91823363,  0.6061432 ],
        [ 0.14924347, -1.1435062 , -1.2591054 ],
        [-1.7354991 ,  0.9891584 , -0.56615967],
        ...,
        [-0.28459358, -0.40983456, -1.2241905 ],
        [-1.8710287 , -1.5922562 ,  1.2056338 ],
        [-0.68352944,  0.6719527 ,  0.23186676]],

       ...,

       

In [63]:
x[0][1]

<tf.Tensor: shape=(32, 3), dtype=float32, numpy=
array([[-0.3115705 ,  0.66871995, -1.3308023 ],
       [-1.3819488 ,  0.5435539 , -0.16147228],
       [-0.46464762, -2.094918  , -2.1984982 ],
       [-0.2046911 , -0.23727772, -0.5309014 ],
       [ 0.11415612, -0.43335378,  1.7197154 ],
       [ 0.2247871 , -0.9618947 , -1.0062859 ],
       [ 1.2589852 ,  0.88575786,  0.29677415],
       [-0.255451  ,  0.42323545, -0.6892477 ],
       [ 0.13131513,  0.6672413 ,  0.03384571],
       [ 0.0801007 , -0.04011651,  0.8227628 ],
       [ 0.44536543, -0.1384732 ,  1.4398662 ],
       [ 0.5934664 ,  1.6005054 ,  0.874411  ],
       [ 1.278546  ,  1.0628078 ,  0.3822292 ],
       [-0.7797377 , -0.25453818, -0.50113255],
       [-1.4259185 , -1.3612572 , -0.6620372 ],
       [-0.2933969 , -0.54191196,  1.2559652 ],
       [-0.12804325,  1.2426788 , -1.5076312 ],
       [ 1.0600209 , -0.02461636,  0.8252461 ],
       [-1.8344785 , -0.80246097,  0.6347203 ],
       [ 1.1670514 ,  0.12043031, -1.19

In [64]:
x[0][1][2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.46464762, -2.094918  , -2.1984982 ], dtype=float32)>

In [65]:
x[2][1][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.8190084>

In [66]:
x[1,9,2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.3715760e+00,  4.5307478e-01, -1.0897681e-03], dtype=float32)>

In [67]:
#4.6.1 切片
x[1:3].shape

TensorShape([2, 32, 32, 3])

In [68]:
x[0,::].shape

TensorShape([32, 32, 3])

In [69]:
x[:,0:28:2,0:28:2,:].shape

TensorShape([4, 14, 14, 3])

In [70]:
x=tf.range(9)

In [71]:
x[8:0:-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1], dtype=int32)>

In [72]:
x[::-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [73]:
x[::-2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0], dtype=int32)>

In [74]:
x=tf.random.normal([4,32,32,3])
x[0,::-2,::-2].shape

TensorShape([16, 16, 3])

In [75]:
x[:,:,:,1].shape

TensorShape([4, 32, 32])

In [76]:
x[0:2,...,1:].shape

TensorShape([2, 32, 32, 2])

In [77]:
x[2:,...].shape

TensorShape([2, 32, 32, 3])

In [78]:
x[...,:2].shape

TensorShape([4, 32, 32, 2])

**4.7 维度变换**

In [79]:
#4.7.1 Reshape
x = tf.range(96)
x.shape

TensorShape([96])

In [80]:
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], dtype=int32)>

In [81]:
x = tf.reshape(x, [2,4,4,3])
x.shape

TensorShape([2, 4, 4, 3])

In [82]:
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [83]:
x.ndim, x.shape

(4, TensorShape([2, 4, 4, 3]))

In [84]:
tf.reshape(x, [2, -1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [85]:
tf.reshape(x,[2,4,12])

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]], dtype=int32)>

In [86]:
tf.reshape(x, [2,-1,3])

<tf.Tensor: shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]], dtype=int32)>

In [87]:
#4.7.2 增删维度
x=tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x.shape

TensorShape([28, 28])

In [88]:
x = tf.expand_dims(x, axis=2)
x.shape

TensorShape([28, 28, 1])

In [89]:
x=tf.expand_dims(x,axis=0)
x.shape

TensorShape([1, 28, 28, 1])

In [90]:
x=tf.squeeze(x,axis=0)
x.shape

TensorShape([28, 28, 1])

In [91]:
x=tf.squeeze(x,axis=2)
x.shape

TensorShape([28, 28])

In [92]:
x=tf.random.uniform([1,28,28,1],maxval=10,dtype=tf.int32)
x.shape

TensorShape([1, 28, 28, 1])

In [93]:
tf.squeeze(x).shape

TensorShape([28, 28])

In [94]:
#4.7.3 交换维度
x = tf.random.normal([2, 32, 32, 3])
x.shape

TensorShape([2, 32, 32, 3])

In [95]:
tf.transpose(x, perm=[0,3,1,2]).shape

TensorShape([2, 3, 32, 32])

In [96]:
tf.transpose(x,perm=[0,2,1,3]).shape

TensorShape([2, 32, 32, 3])

In [97]:
#4.7.4 数据复制
b=tf.constant([1,2])
b=tf.expand_dims(b,axis=0)
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [98]:
b=tf.tile(b,multiples=[2,1])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

In [99]:
x=tf.range(4)
x=tf.reshape(x,[2,2])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [100]:
x=tf.tile(x,multiples=[1,2])
x

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]], dtype=int32)>

In [101]:
x=tf.tile(x,multiples=[2,1])
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]], dtype=int32)>

**4.8 Broadcasting**

In [102]:
x=tf.random.normal([2,4])
w=tf.random.normal([4,3])
b=tf.random.normal([3])
y=x@w+b
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.4075221 ,  0.94388086,  0.4292587 ],
       [-1.5299037 ,  0.44695765,  1.153242  ]], dtype=float32)>

In [103]:
y=x@w+tf.broadcast_to(b,[2,3])
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.4075221 ,  0.94388086,  0.4292587 ],
       [-1.5299037 ,  0.44695765,  1.153242  ]], dtype=float32)>

In [104]:
A=tf.random.normal([32,1])
tf.broadcast_to(A,[2,32,32,3]).shape

TensorShape([2, 32, 32, 3])

In [121]:
#A=tf.random.normal([32,2])
#tf.broadcast_to(A,[2,32,32,3]).shape

In [106]:
a=tf.random.normal([2,32,32,1])
b=tf.random.normal([32,32])

In [107]:
(a+b).shape,(a-b).shape,(a*b).shape,(a/b).shape

(TensorShape([2, 32, 32, 32]),
 TensorShape([2, 32, 32, 32]),
 TensorShape([2, 32, 32, 32]),
 TensorShape([2, 32, 32, 32]))

**4.9 数学运算**

In [ ]:
#4.9.1 加减乘除
a=tf.range(5)
b=tf.constant(2)
a/b

In [109]:
a%b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0], dtype=int32)>

In [110]:
#4.9.2 乘方
x=tf.range(4)
tf.pow(x,3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [111]:
x**2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9], dtype=int32)>

In [112]:
x=tf.constant([1.,4.,9.,])
x**(0.5)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [113]:
x=tf.range(5)
x=tf.cast(x,dtype=tf.float32)
x=tf.square(x)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [114]:
tf.sqrt(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [115]:
#4.9.3 指数、对数
x=tf.constant([1.,2.,3.])
2**x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

In [116]:
tf.exp(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [117]:
x=tf.exp(1.)
tf.math.log(x)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999994>

In [118]:
x=tf.constant([1.,2.])
x=10**x
tf.math.log(x)/tf.math.log(10.)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [119]:
#4.9.4 矩阵相乘
a=tf.random.normal([4,3,23,32])
b=tf.random.normal([4,3,32,2])
(a@b).shape

TensorShape([4, 3, 23, 2])

In [120]:
a=tf.random.normal([4,28,32])
b=tf.random.normal([32,16])
(a@b).shape

TensorShape([4, 28, 16])