本章介紹 TensorFlow 的基本操作

# **TensorFlow 1+1**

In [ ]:
import tensorflow as tf

# 定義一個隨機數（純量）
random_float = tf.random.uniform(shape=())

# 定義一個有2個元素的零向量
zero_vector = tf.zeros(shape=(2))

# 定義兩個2×2的常量矩陣
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])

In [ ]:
# 查看矩陣A的形狀、類型和值
print(A.shape)     # 輸出(2, 2)，即矩陣的長和寬均為2
print(A.dtype)     # 輸出<dtype: 'float32'>
print(A.numpy())    # 輸出[[1. 2.]
            #      [3. 4.]]

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]


In [ ]:
C = tf.add(A, B)   # 計算矩陣A和B的和
D = tf.matmul(A, B) # 計算矩陣A和B的乘積
print(C)
print(D)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


**自動推導機制**

在機器學習中，我們經常需要計算函數的導數。TensorFlow 提供了強大的 自動推導機制 来计算导数。來計算導數。在即時執行模式下，TensorFlow 引入了 tf.GradientTape() 這個 “推導記錄器” 來實現自動微分。以下程式碼展示了如何使用 tf.GradientTape() 計算函數 y(x) = x^2 在 x = 3 時的導數：

In [ ]:
import tensorflow as tf

x = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:     # 在 tf.GradientTape() 的上下文內，所有計算步驟都會被記錄以用於推導
    y = tf.square(x)
y_grad = tape.gradient(y, x)        # 計算y關於x的導數
print(y, y_grad)

tf.Tensor(9.0, shape=(), dtype=float32) tf.Tensor(6.0, shape=(), dtype=float32)


在機器學習中，更加常見的是對多元函數求偏導數，以及對向量或矩陣的推導。這些對於 TensorFlow 也不在話下。以下程式碼展示了如何使用 tf.GradientTape() 計算函數 L(w, b) = \|Xw + b - y\|^2 在 w = (1, 2)^T, b = 1 時分別對 w, b 的偏導數。其中 X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix},  y = \begin{bmatrix} 1 \\ 2\end{bmatrix}。

In [ ]:
X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.], [2.]])
w = tf.Variable(initial_value=[[1.], [2.]])
b = tf.Variable(initial_value=1.)

with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(X, w) + b - y))
w_grad, b_grad = tape.gradient(L, [w, b])        # 計算L(w, b)關於w, b的偏導數
print(L, w_grad, b_grad)

tf.Tensor(125.0, shape=(), dtype=float32) tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32) tf.Tensor(30.0, shape=(), dtype=float32)
