**Sort**

從字面來看就是排序，有時候我們會需要透過sort來排序feature並針對排序後的資料來畫圖或者來檢驗您對資料的假設。又或者我今天講把預測不好的後100筆資料拿出來驗證模型模型問題。都可以使用這樣的方法。這邊會介紹兩種方法，一種是純粹的sort，一種是sort後output是index，你就可以拿index來針對特定feature畫圖。

In [1]:
import tensorflow as tf

#Example for sort
data = tf.random.normal([10], mean=0, stddev=1)
tf.sort(data, direction='DESCENDING')
#or
tf.gather(data, tf.argsort(data, direction='ASCENDING'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-2.1640491 , -1.7597288 , -1.7403909 , -0.9920582 , -0.32427695,
        0.07343318,  0.27338642,  0.6386347 ,  0.7240785 ,  1.2931923 ],
      dtype=float32)>

In [2]:
#Example top_k
top_data = tf.top_k(data,5)
#Get indies or values
top_data.indies
#or
top_data.values

AttributeError: ignored

**Padding**

在做影像辨識的時候，有時候我們會做padding，而padding的作用是什麼呢？1. 針對差異圖片的大小做補齊，有時候可能輸入和filter不一致時，可以透過padding補齊。2. 有時候我們希望增加邊界訊息量，一般來說，沒做padding邊界只會被掃到一次，若做padding可以增加被掃到的次數，這邊簡單的說明padding及example，之後講CNN的時候會更詳細說明。

In [3]:
#Example padding
data = tf.random.normal([3,3], mean=0, stddev=1)
tf.pad(data, [[1,1],[1,1]])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -1.6840906 ,  0.13492478, -1.8575871 ,  0.        ],
       [ 0.        , -0.86056596, -1.1524991 , -1.0469143 ,  0.        ],
       [ 0.        ,  0.01913444, -0.04942415, -1.6121063 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      dtype=float32)>

**Clipping**

有時候我們在做Deep learning在計算gradient的時候，有時候會遇到gradient exploding。我們可預期當一個數字累乘 (1.01**100)，你的gradient會變超大。所以，解決的方法簡單來說就是超過一個門檻值就固定，或者重新使用tf.clip_by_norm，這個方法就比較進階一點，他是針對整個data做縮放

In [4]:
#Example clipping
tf.clip_by_value(data,0,1)
#range if number less or above fix at 0 or 1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.        , 0.13492478, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.01913444, 0.        , 0.        ]], dtype=float32)>

**基本數學運算**

In [5]:
#Example for element wise
a = tf.fill([2,2],5)
b = tf.fill([2,2],6)
a+b,a*b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 11],
        [11, 11]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 30],
        [30, 30]], dtype=int32)>)

In [6]:
#Example for Matrix wise
a = tf.fill([2,32,4],5)
b = tf.fill([2,4,6],6)
(a@b).shape # or tf.matmul(a,b)
#Output:TensorShape([2, 32, 6])

TensorShape([2, 32, 6])

In [7]:
#Example for dimension wise
data = [[1,2,3],
      [1,2,3]]

tf_data = tf.cast(x,tf.float32)

mean_all = tf.reduce_mean(tf_data, keepdims=False)
mean_0 = tf.reduce_mean(tf_data, axis=0, keepdims=False)
mean_1 = tf.reduce_mean(tf_data, axis=1, keepdims=False)

mean_all,mean_0,mean_1

NameError: ignored