In [1]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf

In [2]:
print(tf.add(1,2))
print(tf.add([3,8], [2,5]))
print(tf.square(6))
print(tf.reduce_sum([7,8,9]))
print(tf.square(3)+tf.square(4))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([ 5 13], shape=(2,), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)


In [3]:
x = tf.matmul([[3], [6]], [[2]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[ 6]
 [12]], shape=(2, 1), dtype=int32)
(2, 1)
<dtype: 'int32'>


In [4]:
import numpy as np

ndarray = np.ones([2,2])
tensor = tf.multiply(ndarray, 36)
print(tensor)
print(np.add(tensor, 1))
print(tensor.numpy())

tf.Tensor(
[[36. 36.]
 [36. 36.]], shape=(2, 2), dtype=float64)
[[37. 37.]
 [37. 37.]]
[[36. 36.]
 [36. 36.]]


In [5]:
x = tf.random.uniform([3, 3])
print('Is GPU availabel:')
print(tf.test.is_gpu_available())
print('Is the Tensor on gpu #0:')
print(x.device.endswith('GPU:0'))

Is GPU availabel:
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False
Is the Tensor on gpu #0:
False


In [6]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
    result = time.time() - start
    print('10 loops: {:0.2}ms'.format(1000*result))
    
print('On CPU:')
with tf.device('CPU:0'):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith('CPU:0')
    time_matmul(x)    

if tf.test.is_gpu_available():
    print('On GPU:')
    with tf.device.endswith('GPU:0'):
        x = tf.random.uniform([1000, 1000])
    assert x.device.endswith('GPU:0')
    time_matmul(x)

On CPU:
10 loops: 3.7e+02ms
