In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [2]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(100, input_shape=(None, 20))

In [3]:
layer(tf.ones([6, 6]))

<tf.Tensor: shape=(6, 100), dtype=float32, numpy=
array([[ 2.38118410e-01, -3.25696945e-01,  5.41712224e-01,
        -1.72802508e-02,  1.54555351e-01, -4.17857319e-02,
        -2.92227447e-01,  1.91998348e-01,  7.03573227e-04,
        -7.14081228e-02, -1.70519426e-01,  1.38319194e-01,
         4.30094361e-01,  4.06188607e-01, -5.35149723e-02,
         1.75608993e-02, -2.86691755e-01, -5.50961614e-01,
         4.87338662e-01,  6.98477179e-02,  2.80745238e-01,
        -4.32599962e-01, -2.99310386e-01,  2.83278227e-01,
         3.65616322e-01, -8.43813717e-02, -5.25456071e-01,
        -1.33425668e-01, -1.38317034e-01,  3.75273585e-01,
        -6.52104795e-01, -3.56146693e-01,  4.58657146e-02,
        -3.85678709e-01,  1.93990678e-01, -1.45787492e-01,
         4.21365082e-01,  3.52314800e-01,  2.84699529e-01,
        -1.00557193e-01,  2.53750026e-01,  2.19137758e-01,
        -5.57316482e-01,  1.47955790e-01, -1.21336013e-01,
         2.93096602e-01,  7.27592289e-01, -4.73098010e-02,
      

In [4]:
print(layer.variables)

[<tf.Variable 'dense_1/kernel:0' shape=(6, 100) dtype=float32, numpy=
array([[-0.00550404,  0.00177142,  0.08941026, -0.18362698,  0.00441706,
        -0.14303276, -0.21861792,  0.07140346,  0.08595704,  0.18406205,
        -0.00337918, -0.09519066, -0.20318642,  0.22255526, -0.1631267 ,
         0.18613113,  0.0175959 , -0.16438988, -0.06950445,  0.12862273,
         0.14537476, -0.16189383, -0.23339586,  0.20402001,  0.21993656,
        -0.08775347, -0.15539002, -0.01037529, -0.09778474,  0.08845524,
         0.01403503, -0.2147032 ,  0.18291976,  0.22408469,  0.19681619,
         0.10344477,  0.17378591,  0.10746799,  0.00185327,  0.11260833,
         0.14392684, -0.0315358 , -0.19338992,  0.20058168, -0.09214228,
        -0.07876337,  0.15485324, -0.18477046, -0.12936366, -0.03517967,
         0.15413405,  0.07374708,  0.10868438, -0.1471059 , -0.20466928,
        -0.02436511, -0.07344981, -0.03068405,  0.12609337,  0.21841718,
        -0.07769902, -0.20508394, -0.11648652, -0.1802

In [5]:
print(layer.kernel, layer.bias)

<tf.Variable 'dense_1/kernel:0' shape=(6, 100) dtype=float32, numpy=
array([[-0.00550404,  0.00177142,  0.08941026, -0.18362698,  0.00441706,
        -0.14303276, -0.21861792,  0.07140346,  0.08595704,  0.18406205,
        -0.00337918, -0.09519066, -0.20318642,  0.22255526, -0.1631267 ,
         0.18613113,  0.0175959 , -0.16438988, -0.06950445,  0.12862273,
         0.14537476, -0.16189383, -0.23339586,  0.20402001,  0.21993656,
        -0.08775347, -0.15539002, -0.01037529, -0.09778474,  0.08845524,
         0.01403503, -0.2147032 ,  0.18291976,  0.22408469,  0.19681619,
         0.10344477,  0.17378591,  0.10746799,  0.00185327,  0.11260833,
         0.14392684, -0.0315358 , -0.19338992,  0.20058168, -0.09214228,
        -0.07876337,  0.15485324, -0.18477046, -0.12936366, -0.03517967,
         0.15413405,  0.07374708,  0.10868438, -0.1471059 , -0.20466928,
        -0.02436511, -0.07344981, -0.03068405,  0.12609337,  0.21841718,
        -0.07769902, -0.20508394, -0.11648652, -0.18022