In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
csv_data = tf.keras.utils.get_file('iris.csv', 'https://raw.githubusercontent.com/jerrywu2013/Hiskio_data/master/iris.csv')

8192/3975 [=============================================================] - 0s 0us/step


In [3]:
df = pd.read_csv(csv_data)

In [4]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [5]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [6]:
#轉換目標欄位為離散值
df['variety'] = pd.Categorical(df['variety'])

In [7]:
df.dtypes

sepal.length     float64
sepal.width      float64
petal.length     float64
petal.width      float64
variety         category
dtype: object

In [8]:
df['variety'] = df.variety.cat.codes

In [9]:
df.head()

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [10]:
#透過tf.data.Dataset做資料切割與轉換

In [11]:
target = df.pop('variety')

In [12]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [13]:
#透過tf.data.Dataset可以轉換標準的Tensor資料管道方便之後運算
dataset

<TensorSliceDataset shapes: ((4,), ()), types: (tf.float64, tf.int8)>

In [14]:
#觀察資料
for i in dataset.take(20):
  print (i)

(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5.1, 3.5, 1.4, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.9, 3. , 1.4, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.7, 3.2, 1.3, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.6, 3.1, 1.5, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5. , 3.6, 1.4, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5.4, 3.9, 1.7, 0.4])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.6, 3.4, 1.4, 0.3])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5. , 3.4, 1.5, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, 

In [15]:
#將資料根據資料列數進行shuffle
all_train_dataset = dataset.shuffle(len(df)).batch(1)

In [16]:
#觀察資料
for i in all_train_dataset.take(20):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.4, 3.2, 4.5, 1.5]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.4, 3.4, 1.5, 0.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.2, 2.9, 4.3, 1.3]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6. , 2.9, 4.5, 1.5]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.7, 3.1, 4.4, 1.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[7.4, 2.8, 6.1, 1.9]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[7.2, 3.6, 6.1, 2.5]])>, <tf.Tensor: shape=(1,), dtype=int8, nu

In [17]:
train_dataset = all_train_dataset.take(int(0.7 * len(df)))
test_dataset = all_train_dataset.skip(int(0.7 * len(df)))

In [18]:
for i in test_dataset.take(20):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6. , 3.4, 4.5, 1.6]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.7, 3.1, 5.6, 2.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.9, 3. , 5.1, 1.8]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.3, 3.7, 1.5, 0.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[4.8, 3.1, 1.6, 0.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.4, 2.8, 5.6, 2.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.1, 2.8, 4.7, 1.2]])>, <tf.Tensor: shape=(1,), dtype=int8, nu

In [19]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3)
])

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) 
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(train_dataset, epochs=10)

Epoch 1/10
105/105 [==============================] - 1s 1ms/step - loss: 1.2237 - accuracy: 0.4155
Epoch 2/10
105/105 [==============================] - 0s 1ms/step - loss: 0.8213 - accuracy: 0.6583
Epoch 3/10
105/105 [==============================] - 0s 1ms/step - loss: 0.6117 - accuracy: 0.7378
Epoch 4/10
105/105 [==============================] - 0s 1ms/step - loss: 0.6049 - accuracy: 0.6985
Epoch 5/10
105/105 [==============================] - 0s 1ms/step - loss: 0.4797 - accuracy: 0.7684
Epoch 6/10
105/105 [==============================] - 0s 1ms/step - loss: 0.4071 - accuracy: 0.8746
Epoch 7/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3988 - accuracy: 0.8496
Epoch 8/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3537 - accuracy: 0.8607
Epoch 9/10
105/105 [==============================] - 0s 1ms/step - loss: 0.2565 - accuracy: 0.8962
Epoch 10/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.9370

In [21]:
model.evaluate(test_dataset)

45/45 [==============================] - 0s 869us/step - loss: 0.3195 - accuracy: 0.8000


[0.31951022148132324, 0.800000011920929]

In [22]:
for i in test_dataset.take(1):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.4, 3.9, 1.3, 0.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)


In [23]:
pred = model.predict([[5.4, 3.4, 1.5, 0.4]])
np.argmax(pred)

0