##第一個TF Hello World（簡單版）

In [1]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=88)

In [2]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3)
])

In [3]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) 
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 4ms/step - loss: 1.6010 - accuracy: 0.3472
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.3714 - accuracy: 0.3476
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.2274 - accuracy: 0.3892
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1317 - accuracy: 0.3933
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1455 - accuracy: 0.3534
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0960 - accuracy: 0.3649
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0054 - accuracy: 0.4391
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0320 - accuracy: 0.3874
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9952 - accuracy: 0.4894
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9137 - accuracy: 0.5581
Epoch 11/100
4/4 [===========

In [4]:
model.evaluate(x_test,  y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.2502 - accuracy: 0.9556


[0.2501556873321533, 0.9555555582046509]

In [5]:
x_test[0]

array([5.4, 3. , 4.5, 1.5])

In [6]:
y_test[0]

1

In [7]:
pred = model.predict([[5.4, 3. , 4.5, 1.5]])
np.argmax(pred)

1

## 第一個TF Hello World(專家版)

In [8]:
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Flatten

In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=88)

In [10]:
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)
test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

In [11]:
for iris_data, iris_labels in train_ds:
  print(iris_data, iris_labels)

tf.Tensor(
[[6.3 2.9 5.6 1.8]
 [6.3 2.3 4.4 1.3]
 [4.4 2.9 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [4.8 3.  1.4 0.1]
 [6.4 2.8 5.6 2.1]
 [6.1 3.  4.6 1.4]
 [6.8 2.8 4.8 1.4]
 [5.  3.4 1.6 0.4]
 [4.9 3.1 1.5 0.1]
 [5.8 2.8 5.1 2.4]
 [5.5 2.4 3.7 1. ]
 [6.5 3.  5.2 2. ]
 [6.7 3.3 5.7 2.1]
 [5.8 2.7 3.9 1.2]
 [4.7 3.2 1.3 0.2]
 [5.6 2.9 3.6 1.3]
 [6.3 2.5 5.  1.9]
 [6.6 2.9 4.6 1.3]
 [6.  2.7 5.1 1.6]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.1 3.8 1.9 0.4]
 [5.  3.5 1.6 0.6]
 [6.4 2.9 4.3 1.3]
 [5.7 3.8 1.7 0.3]
 [6.3 2.5 4.9 1.5]
 [5.3 3.7 1.5 0.2]
 [6.5 3.2 5.1 2. ]
 [4.6 3.4 1.4 0.3]
 [7.7 3.  6.1 2.3]
 [5.  3.2 1.2 0.2]], shape=(32, 4), dtype=float64) tf.Tensor([2 1 0 2 0 2 1 1 0 0 2 1 2 2 1 0 1 2 1 1 1 1 0 0 1 0 1 0 2 0 2 0], shape=(32,), dtype=int64)
tf.Tensor(
[[5.  3.6 1.4 0.2]
 [6.3 3.4 5.6 2.4]
 [5.  2.3 3.3 1. ]
 [5.2 3.5 1.5 0.2]
 [5.7 2.6 3.5 1. ]
 [7.2 3.2 6.  1.8]
 [6.4 3.2 5.3 2.3]
 [6.3 3.3 4.7 1.6]
 [5.  3.3 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [6.5 2.8 4.6 1.5]
 [4.9 3.6 1.4 0.1]
 [5.9 3

In [12]:
class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.flatten = Flatten()
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(3)

  def call(self, x):
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)


model = MyModel()

In [13]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam()

In [14]:
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss') 
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')

In [15]:
@tf.function
def train_step(iris_data, iris_labels):
  with tf.GradientTape() as tape: #tf.GradientTape訓練模型
    predictions = model(iris_data, training=True) #確認訓練來源
    loss = loss_object(iris_labels, predictions) #建立Loss運算來源
  gradients = tape.gradient(loss, model.trainable_variables) #backward 反向傳播
  optimizer.apply_gradients(zip(gradients, model.trainable_variables)) #取得訓練的權重、偏移量優化

  train_loss(loss)
  train_accuracy(iris_labels, predictions)

In [16]:
@tf.function
def test_step(iris_data, iris_labels):
  predictions = model(iris_data, training=False) #training=False 表示測試資料進行測試
  t_loss = loss_object(iris_labels, predictions) #建立Loss

  test_loss(t_loss)
  test_accuracy(iris_labels, predictions)

In [17]:
EPOCHS = 50

for epoch in range(EPOCHS):
  #每一次epoch的時候做重整
  train_loss.reset_states()
  train_accuracy.reset_states()
  test_loss.reset_states()
  test_accuracy.reset_states()

  for iris_data, iris_labels in train_ds:
    train_step(iris_data, iris_labels)

  for test_iris_data, test_iris_labels in test_ds:
    test_step(test_iris_data, test_iris_labels)

  template = '迭代 {}, 訓練資料損失: {}, 訓練資料準確率: {}, 測試資料損失: {}, 測試資料準確率: {}'
  print(template.format(epoch+1,
                        train_loss.result(),
                        train_accuracy.result()*100,
                        test_loss.result(),
                        test_accuracy.result()*100))

迭代 1, 訓練資料損失: 1.179337739944458, 訓練資料準確率: 52.38095474243164, 測試資料損失: 1.200178623199463, 測試資料準確率: 24.44444465637207
迭代 2, 訓練資料損失: 1.0623770952224731, 訓練資料準確率: 37.14285659790039, 測試資料損失: 1.061021089553833, 測試資料準確率: 22.22222328186035
迭代 3, 訓練資料損失: 0.9984710812568665, 訓練資料準確率: 31.428571701049805, 測試資料損失: 0.9723754525184631, 測試資料準確率: 33.333335876464844
迭代 4, 訓練資料損失: 0.9500128626823425, 訓練資料準確率: 26.666667938232422, 測試資料損失: 0.9142277836799622, 測試資料準確率: 42.22222137451172
迭代 5, 訓練資料損失: 0.8975378274917603, 訓練資料準確率: 44.761905670166016, 測試資料損失: 0.8720155358314514, 測試資料準確率: 60.000003814697266
迭代 6, 訓練資料損失: 0.8458622694015503, 訓練資料準確率: 72.38095092773438, 測試資料損失: 0.8344491720199585, 測試資料準確率: 62.222225189208984
迭代 7, 訓練資料損失: 0.8002098202705383, 訓練資料準確率: 74.28571319580078, 測試資料損失: 0.7934244871139526, 測試資料準確率: 66.66667175292969
迭代 8, 訓練資料損失: 0.7594889402389526, 訓練資料準確率: 75.23809814453125, 測試資料損失: 0.749601423740387, 測試資料準確率: 68.8888931274414
迭代 9, 訓練資料損失: 0.7225885987281799, 訓練資料準確率: 80.95238494873047, 測