2.2.1 Sigmoid激活函數

In [1]:
%tensorflow_version 1.x

import tensorflow
print(tensorflow.__version__)

TensorFlow 1.x selected.
1.15.2


In [2]:
import tensorflow as tf

t = tf.constant([[1,2],[2,0]], tf.float32)
result = tf.nn.sigmoid(t)
session = tf.Session()
session.run(result)

array([[0.7310586, 0.880797 ],
       [0.880797 , 0.5      ]], dtype=float32)

2.2.2 Tanh激活函數

In [3]:
import tensorflow as tf

t = tf.constant([[1,2],[2,0]], tf.float32)
result = tf.nn.tanh(t)
session = tf.Session()
session.run(result)

array([[0.7615942, 0.9640276],
       [0.9640276, 0.       ]], dtype=float32)

2.2.3 ReLU激活函數


In [4]:
import tensorflow as tf

t = tf.constant([[1,2],[2,0]], tf.float32)
result = tf.nn.relu(t)
session = tf.Session()
session.run(result)

array([[1., 2.],
       [2., 0.]], dtype=float32)