In [1]:
%tensorflow_version 1.x

import tensorflow
print(tensorflow.__version__)

TensorFlow 1.x selected.
1.15.2


same捲積: 捲積前後像素矩陣保持同樣維度

In [4]:
import tensorflow as tf

X = tf.constant(
    [
     [
      [[3],[-1],[3]],
      [[9],[2],[4]],
      [[8],[1],[5]]
     ]
    ],
    tf.float32
)

K = tf.constant(
    [
     [
      [[5]],[[2]]],
     [
      [[1]],[[3]]
     ]
    ],
    tf.float32
)

conv = tf.nn.conv2d(X, K, (1,1,1,1), 'SAME')
session = tf.Session()
print(session.run(conv))

[[[[28.]
   [15.]
   [19.]]

  [[60.]
   [34.]
   [25.]]

  [[42.]
   [15.]
   [25.]]]]


valid捲積: 要求捲積核完全被覆蓋在像素矩陣的有效範圍內

In [5]:
X = tf.constant(
    [
     [
      [[3],[-1],[3]],
      [[9],[2],[4]],
      [[8],[1],[5]]
     ]
    ],
    tf.float32
)

K = tf.constant(
    [
     [
      [[5]],[[2]]],
     [
      [[1]],[[3]]
     ]
    ],
    tf.float32
)

conv = tf.nn.conv2d(X, K, (1,1,1,1), 'VALID')
session = tf.Session()
print(session.run(conv))

[[[[28.]
   [15.]]

  [[60.]
   [34.]]]]
