In [1]:
#因為範例為1.X版本的程式,所以要降版
%tensorflow_version 1.x

import tensorflow as tf
tf.__version__

TensorFlow 1.x selected.


'1.15.2'

In [2]:
import tensorflow as tf
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

print("##Example 1: matrix : addtion: a + b")
a   = tf.constant([[1,2],[3,4]])
b   = tf.constant([[5,6],[7,8]])
add = a + b
with tf.Session() as sess:
  print("a = \n" + str(sess.run(a)))
  print("b = \n" + str(sess.run(b)))
  print("a + b = \n" + str(sess.run(add)))

print("\n##Example 2: matrix : subtract: b - a")
a   = tf.constant([[1,2],[3,4]])
b   = tf.constant([[5,6],[7,8]])
sub = tf.subtract(b,a)
with tf.Session() as sess:
  print("a = \n" + str(sess.run(a)))
  print("b = \n" + str(sess.run(b)))
  print("tf.subtract(b,a)  = \n" + str(sess.run(sub)))

print("\n##Example 3: matrix : multiply: a*b")
a   = tf.constant([[1,2],[3,4]])
b   = tf.constant([[5,6],[7,8]])
mul = tf.matmul(a,b)
with tf.Session() as sess:
  print("a = \n" + str(sess.run(a)))
  print("b = \n" + str(sess.run(b)))
  print("tf.matmul(a,b)  = \n" + str(sess.run(mul)))

print("\n##Example 4: matrix : inverse matrix of a: ")
a       = tf.constant([[1.,2.],[3.,4.]])
inverse = tf.matrix_inverse(a)
with tf.Session() as sess:
  print("a = \n" + str(sess.run(a)))
  print("tf.matrix_inverse(a)  = \n" + str(sess.run(inverse)))

print("\n##Example 5: matrix : transpose matrix of a: ")
a         = tf.constant([[1.,2.],[3.,4.]])
transpose = tf.transpose(a)
with tf.Session() as sess:
  print("a = \n" + str(sess.run(a)))
  print("tf.transpose(a)  = \n" + str(sess.run(transpose)))

print("\n##Example 6: matrix : diag matrix of a: ")
a         = tf.constant([1,2,3,4])
diagmatrix= tf.matrix_diag(a)
with tf.Session() as sess:
  print("a = \n" + str(sess.run(a)))
  print("tf.matrix_diag(a)  = \n" + str(sess.run(diagmatrix)))

##Example 1: matrix : addtion: a + b
a = 
[[1 2]
 [3 4]]
b = 
[[5 6]
 [7 8]]
a + b = 
[[ 6  8]
 [10 12]]

##Example 2: matrix : subtract: b - a
a = 
[[1 2]
 [3 4]]
b = 
[[5 6]
 [7 8]]
tf.subtract(b,a)  = 
[[4 4]
 [4 4]]

##Example 3: matrix : multiply: a*b
a = 
[[1 2]
 [3 4]]
b = 
[[5 6]
 [7 8]]
tf.matmul(a,b)  = 
[[19 22]
 [43 50]]

##Example 4: matrix : inverse matrix of a: 
a = 
[[1. 2.]
 [3. 4.]]
tf.matrix_inverse(a)  = 
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

##Example 5: matrix : transpose matrix of a: 
a = 
[[1. 2.]
 [3. 4.]]
tf.transpose(a)  = 
[[1. 3.]
 [2. 4.]]

##Example 6: matrix : diag matrix of a: 
a = 
[1 2 3 4]
tf.matrix_diag(a)  = 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
